### ISSUE TITLE
Transfer Repo

### ISSUE THREAD

**Issue by sbatson5** [sbatson5/firestore-jest-mock#172]
@mgburns Can I have this repo transferred to me? It will not be maintained otherwise

**Comment by mgburns** [comment]
Hey @sbatson5 -- we're discussing this internally and will get back to you by tomorrow.

**Comment by mgburns** [comment]
@sbatson5 Thank you for the offer, and for all of the work you put into this project over the years. We'd be happy to hand over the keys to better serve the community.

GitHub doesn't support transfers from organizations to personal accounts that aren't owners within the transferring organization. As such, I'll need to transfer to my personal account first and then transfer to you. Are you around today to accept the transfer?

**Comment by sbatson5** [comment]
@mgburns Yup, I'm online for the next few hours. No rush if we can't make it work today

**Comment by sbatson5** [comment]
As a note, I'll also need npm access

**Comment by mgburns** [comment]
@sbatson5 Good call -- do you have an NPM account for that transfer?

**Comment by sbatson5** [comment]
https://www.npmjs.com/~sbatson5

**Comment by mgburns** [comment]
@sbatson5 Transfer request should be in your inbox for this repo. There should also be an invite from NPM to maintain the [firestore-jest-mock package](https://www.npmjs.com/package/firestore-jest-mock/access).

**Comment by sbatson5** [comment]
@mgburns can you try resending both? I think they were trying to send to an old email I don't use anymore

**Comment by mgburns** [comment]
@sbatson5 Done
