### ISSUE TITLE
Mock the unsubscribe callback returned by onSnapshot

### ISSUE THREAD

**Issue by shaoshiva** [sbatson5/firestore-jest-mock#189]
Hi,

# Summary

I would like to be able to test that the unsubscribe callback returned by `onSnapshot` is called.

## Basic example

Let's say we have a React component that subscribes on mount and unsubscribes on unmount:

```tsx
const MyComponent = () => {
    useEffect(() => {
        const unsubscribe = firestore().collection('test').onSnapshot(() => {
            console.log('Got a snapshot');
        });

        return () => {
            unsubscribe();
        };
    }, []);

    return (...);
}
```

I would like to test that the unsubscribe callback is called on unmount, but this seems currently impossible because the mocked `onSnapshot` function returns an anonymous function:

```ts
class Query {
    ...
    onSnapshot() {
        ...
        // Returns an unsubscribe function
        return () => { };
  }
}
```

Instead, it could return a mock function that is exported by the module:

```ts
const mockQueryOnSnapshotUnsubscribe = jest.fn();

class Query {
    ...
    onSnapshot() {
        ...
        // Returns an unsubscribe function
        return mockQueryOnSnapshotUnsubscribe;
  }
}

module.exports = {
    Query,
    mocks: {
        ...
        mockQueryOnSnapshotUnsubscribe,
    },
};
```

With that, I could write the following test:

```ts
import { mockQueryOnSnapshotUnsubscribe } from 'firestore-jest-mock/mocks/firestore';

describe('MyComponent', () => {
    it('should unsubscribe on umount', () => {
        const { unmount } = render(<MyComponent />);
        expect(mockQueryOnSnapshotUnsubscribe).toHaveBeenCalledTimes(0);
        unmount();
        expect(mockQueryOnSnapshotUnsubscribe).toHaveBeenCalledTimes(1);
    });
});
```

## Motivation

Have a better test coverage by being able to assert that the unsubscribe callback is called.

Thanks for your time.

**Comment by sbatson5** [comment]
Makes sense to me. Did you want to open a PR for this? If not, I can take a stab at it tomorrow

**Comment by shaoshiva** [comment]
Sure, I will open a PR!
